services:
  - type: web
    name: oneminute-exercises
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /
        destination: /index.html
